### PR TITLE
Add feature reset password

### PR DESCRIPTION
**Pull request by hyesun03**
* You can reset password
* I wonder why 'reset password page' is at admin page.

### CODE REVIEW

**Comment by guswnsxodlf** [comment]
First of all, I've just read Django docs and Django-registration, I don't know how it works that using url 'auth_password_reset', not 'password_reset'.
There is no mention about 'auth_password_reset'.
Give me url you referred or followed.

**Comment by hyesun03** [comment]
https://docs.djangoproject.com/en/1.10/topics/auth/default/
http://ruddra.com/2015/09/18/implementation-of-forgot-reset-password-feature-in-django/

**Comment by hyesun03** [comment]
issue #135

**Comment by hyesun03** [comment]
이 커밋의 상위 커밋 3개가 #126 PR과 겹칩니다.

**Pull request closed without merging**
